In [1]:
import numpy as np
import pandas as pd

In [59]:
# SlavesNum = 1
time_1 = 5077
centers_1 = [[4.989473684210526, 3.313157894736842, 1.4999999999999996, 0.24736842105263157],
             [5.058333333333334, 3.75, 1.3499999999999999, 0.2333333333333334],
             [6.261999999999999, 2.872000000000001, 4.906000000000001, 1.6760000000000006]]

In [47]:
data_1 = pd.read_csv(r"E:\研一下\分布式计算\final\datasets\iris_noclass_blank.data",names = [0,1,2,3])

In [48]:
data_1.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [60]:
distances_1 = np.zeros((data_1.shape[0], len(centers_1)))  # 创建距离矩阵
for i in range(len(centers_1)):  # 0 1 2
    distances_1[:, i] = np.linalg.norm(data_1.values - centers_1[i], axis=1)

In [6]:
distances_1.shape

(150, 3)

In [7]:
distances_1[:5]

array([[0.17619805, 3.49751323, 5.14485667],
       [0.42916548, 3.48166389, 5.20334933],
       [0.41969488, 3.65273117, 5.36668565],
       [0.50996604, 3.50695775, 5.24181352],
       [0.22937824, 3.54561251, 5.18914224]])

In [61]:
labels = np.argmin(distances_1, axis=1)

In [62]:
labels

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [52]:
# 下面读取true_lables
data_true = pd.read_csv(r"E:\研一下\分布式计算\final\datasets\iris.data",names= [0,1,2,3])

In [53]:
data_true.iloc[:,-1].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [63]:
true_labels = []
for item in data_true.iloc[:,-1]:
    if item == "Iris-setosa":
        true_labels.append(1)
    elif item == "Iris-versicolor":
        true_labels.append(0)
    else:
        true_labels.append(2)

In [64]:
true_labels = np.array(true_labels)
true_labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [65]:
sum(labels == true_labels)/150

0.4666666666666667

In [66]:
from sklearn.metrics import adjusted_rand_score

In [67]:
# 假设有两个标签列表：labels和true_labels
rand_index = adjusted_rand_score(labels, true_labels)
print("Adjusted Rand Index:", rand_index)

Adjusted Rand Index: 0.43028672595580375
